-- AlterTable
ALTER TABLE "company" ALTER COLUMN "yearlyHighPrice" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "yearlyLowPrice" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "closePrice" SET DATA TYPE DECIMAL(65,30);
